### ISSUE TITLE
Upload failures don't report very much info to the user

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/sourcemap-upload-webpack-plugin#1]
Someone saw the following output from the webpack plugin:

```
Uploading build/static/js/0.562fa597.chunk.js.map
Uploading build/static/js/1.3ec417ff.chunk.js.map
Uploading build/static/js/1.8bd4624a.chunk.worker.js.map
[webpack-cli] Error: Unexpected error uploading sourcemap
    at uploadSourcemapToAPI (/workspaces/glide/app/node_modules/@recordreplay/sourcemap-upload/lib/index.js:119:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async processSourceMaps (/workspaces/glide/app/node_modules/@recordreplay/sourcemap-upload/lib/index.js:96:13)
    at async ReplaySourceMapUploadWebpackPlugin.afterAssetEmit (/workspaces/glide/app/node_modules/@recordreplay/sourcemap-upload-webpack-plugin/lib/index.js:32:9)
```

I see a corresponding 500 in our backend, but there's not enough information to correlate it there. It would be nice if this showed what request failed, with what error code, etc.

**Comment by jasonLaster** [comment]
@jazzdan is this still relevant.

**Comment by jazzdan** [comment]
@jasonLaster I believe so.

**Comment by loganfsmyth** [comment]
I lumped this into https://github.com/RecordReplay/sourcemap-upload/pull/2
